[package]
name = "sample"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
solana-program = "1.4.8"

[dev-dependencies]
solana-sdk = "1.4.8"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]