[package]
name = "rust-regression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-machine = "0.5.4"
serde = "1.0.144"
serde_derive = "1.0.144"
read_csv = {path = "../../read_csv"}